on: push
name: Build
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test
      uses: actions/action-builder/shell@master
      with:
        entrypoint: make
        args: test
    - name: Lint
      uses: actions/action-builder/shell@master
      with:
        entrypoint: make
        args: lint
    - name: Docker build
      uses: actions/action-builder/docker@master
      with:
        entrypoint: make
        args: build
    - name: Publish Filter
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Docker Login
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Publish
      uses: actions/action-builder/docker@master
      with:
        entrypoint: make
        args: publish
